name: Test Backend

on:
  push:
    branches:
      - test  # Ejecutar las pruebas cuando se realice un push en la rama `test`

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ajusta la versión de Python según sea necesario

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instalar las dependencias necesarias

    - name: Run tests and generate report
      run: |
        mkdir -p reports  # Crear la carpeta 'reports' si no existe
        # Ejecutar las pruebas en todas las carpetas de `tests/` y generar un reporte HTML
        PYTHONPATH=./ pytest --maxfail=5 --disable-warnings --html=reports/test_report.html test/
        
    - name: Upload test report
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: reports/test_report.html  # Sube el reporte HTML generado como artefacto

    - name: Display report summary
      run: |
        echo "Test report is available here:"
        echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
