name: Test 

on:
  push:
    branches:
      - test # Esta es la rama que va a ejecutar las pruebas automáticamente

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Elige la versión que estés utilizando

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Si tienes un archivo de dependencias

    - name: Run Tests
      run: |
        pytest  
