name: Test Backend

on:
  push:
    branches:
      - test  # Las pruebas se ejecutan cuando hay cambios en la rama `test`

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Run all tests
      run: |
        pytest tests/  
