name: Deploy to Render  # Nombre del workflow

on:
  push:
    branches:
      - main  # Se ejecutar치 cuando haya cambios en la rama "main"

jobs:
  deploy:
    runs-on: ubuntu-latest  # M치quina virtual en la que se ejecutar치n los pasos

    steps:
    - name: Checkout Code  # Descarga el c칩digo del repositorio
      uses: actions/checkout@v2

    - name: Build Docker Image  # Construye la imagen Docker
      run: docker build -t disriego/backend-distrito-riego:latest .

    - name: Push Docker Image to Docker Hub  # Subir la imagen a Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag usuario/backend-distrito-riego:latest usuario/backend-distrito-riego:${{ github.sha }}
        docker push usuario/backend-distrito-riego:latest

    - name: Deploy to Render  # Enviar un trigger para que Render haga el despliegue
      run: curl -X POST https://api.render.com/deploy/srv-cuvspiaj1k6c7389m8k0?key=${{ secrets.RENDER_API_KEY }}
